# syntax=docker/dockerfile:1
FROM ubuntu:22.04
MAINTAINER heiko.stein@etomer.com

RUN apt-get update -y
RUN apt-get upgrade -y

RUN mkdir /script

WORKDIR /script

COPY write_log.sh /script

RUN chmod 755 /script/write_log.sh

CMD ["/script/write_log.sh"]
