FROM ubuntu

ARG password

RUN apt update -y
RUN apt upgrade -y
RUN apt install openssh-server -y
RUN apt install sshpass -y
RUN ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
RUN sshpass -p ${password} ssh-copy-id -o StrictHostKeyChecking=no root@websrv

RUN chmod 0777 /root/changes.sh

CMD ["./root/changes.sh"]
